CLASS LCL_HANDLER DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEBOOKINGID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Booking~CalculateBookingID .
ENDCLASS.

CLASS LCL_HANDLER IMPLEMENTATION.
  METHOD CALCULATEBOOKINGID.
  ENDMETHOD.
ENDCLASS.
